fragment GlobalParts on Global {
  __typename
  primaryColor
  secondaryColor
  accentColor
}

fragment PageParts on Page {
  __typename
  title
  blocks {
    __typename
    ... on PageBlocksHero {
      headline
      subheadline
      primaryButtonText
      primaryButtonLink
      secondaryButtonText
      secondaryButtonLink
    }
    ... on PageBlocksStats {
      statItems {
        __typename
        value
        label
      }
    }
    ... on PageBlocksFeatures {
      featureItems {
        __typename
        title
        description
        iconName
      }
    }
    ... on PageBlocksRichText {
      heading
      body
    }
    ... on PageBlocksFaq {
      title
      questions {
        __typename
        question
        answer
      }
    }
    ... on PageBlocksProcess {
      title
      subtitle
      steps {
        __typename
        title
        description
      }
    }
    ... on PageBlocksServicesGrid {
      title
      services {
        __typename
        title
        description
        iconName
        tags
      }
    }
    ... on PageBlocksResourcesList {
      title
      subtitle
      resources {
        __typename
        label
        url
      }
    }
    ... on PageBlocksCategories {
      title
      linkText
      linkUrl
      items {
        __typename
        title
        description
        iconName
      }
    }
    ... on PageBlocksCta {
      title
      description
      buttonText
      buttonLink
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  date
  body
}
